# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Ignore patterns for known issues
paths:
  .github/workflows/**/*.yml:
    ignore:
      # Ignore shellcheck warnings (we run shellcheck separately)
      - "shellcheck reported issue.+"
