#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${SPECIAL_AGENT_INSTALL_E2E_IMAGE:-${SPECIAL_AGENT_INSTALL_E2E_IMAGE:-special-agent-install-e2e:local}}"
INSTALL_URL="${SPECIAL_AGENT_INSTALL_URL:-${SPECIAL_AGENT_INSTALL_URL:-https://special-agent.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
SPECIAL_AGENT_E2E_MODELS="${SPECIAL_AGENT_E2E_MODELS:-${SPECIAL_AGENT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e SPECIAL_AGENT_INSTALL_URL="$INSTALL_URL" \
  -e SPECIAL_AGENT_INSTALL_TAG="${SPECIAL_AGENT_INSTALL_TAG:-${SPECIAL_AGENT_INSTALL_TAG:-latest}}" \
  -e SPECIAL_AGENT_E2E_MODELS="$SPECIAL_AGENT_E2E_MODELS" \
  -e SPECIAL_AGENT_INSTALL_E2E_PREVIOUS="${SPECIAL_AGENT_INSTALL_E2E_PREVIOUS:-${SPECIAL_AGENT_INSTALL_E2E_PREVIOUS:-}}" \
  -e SPECIAL_AGENT_INSTALL_E2E_SKIP_PREVIOUS="${SPECIAL_AGENT_INSTALL_E2E_SKIP_PREVIOUS:-${SPECIAL_AGENT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
